"""
ScreenWeave Playwright Crawler
==============================
Crawls a target URL and captures every visual state encountered, including
interactive UI changes (tabs, accordions, etc.), for downstream visual QA agents.

Configuration (via environment variables set by the calling bash script):
  SCREENWEAVE_SESSION_ID      UUID for this run (pre-generated by startCrawl Lambda)
  SCREENWEAVE_MAX_DEPTH       Link recursion depth (default: 2)
  SCREENWEAVE_MAX_LINKS       Max child links per page (default: 12)
  SCREENWEAVE_DYNAMO_TABLE    DynamoDB table to write session status to
  SCREENWEAVE_S3_BUCKET       S3 bucket (used in artifact_manifest S3 URIs)
  SCREENWEAVE_S3_PREFIX       S3 key prefix root (default: screenweave)
  SCREENWEAVE_REGION          AWS region for boto3 clients

Artifacts written to OUT_DIR (/opt/output):
  .session_id               UUID of this run (also read from env if available)
  screenshots/
    state_0001.png           One file per captured state
    state_0002.png
    ...
  states.json                Structured metadata for every state
  transitions.json           Edge list connecting states
  trace.zip                  Playwright trace (playwright show-trace trace.zip)

DynamoDB writes:
  On start:      status = RUNNING
  On completion: status = COMPLETED, summary_stats, artifact_manifest, updated_at
  On error:      status = FAILED (handled by the calling bash script)
"""

import asyncio
import json
import os
import re
import subprocess
import sys
import uuid
from datetime import datetime, timezone
from urllib.parse import urlparse

from playwright.async_api import async_playwright

# ── Config from environment (set by startCrawl Lambda UserData) ───────────────
BASE_URL    = sys.argv[1]
OUT_DIR     = "/opt/output"
SCREENS_DIR = f"{OUT_DIR}/screenshots"
TRACE_PATH  = f"{OUT_DIR}/trace.zip"

# If launched by startCrawl Lambda, SESSION_ID is pre-generated; else create one.
SESSION_ID  = os.environ.get("SCREENWEAVE_SESSION_ID") or str(uuid.uuid4())
MAX_DEPTH   = int(os.environ.get("SCREENWEAVE_MAX_DEPTH", "2"))
MAX_LINKS   = int(os.environ.get("SCREENWEAVE_MAX_LINKS", "12"))

DYNAMO_TABLE = os.environ.get("SCREENWEAVE_DYNAMO_TABLE", "")
S3_BUCKET    = os.environ.get("SCREENWEAVE_S3_BUCKET", "")
S3_PREFIX    = os.environ.get("SCREENWEAVE_S3_PREFIX", "screenweave")
REGION       = os.environ.get("SCREENWEAVE_REGION", os.environ.get("AWS_REGION", "us-east-1"))

os.makedirs(SCREENS_DIR, exist_ok=True)

# ── Runtime state ─────────────────────────────────────────────────────────────
seen        = set()
states      = []
transitions = []
state_ctr   = [0]
prev_state  = [None]


# ── DynamoDB helpers ──────────────────────────────────────────────────────────

def _dynamo_client():
    """Return a boto3 DynamoDB client. Only imported if DYNAMO_TABLE is set."""
    import boto3
    return boto3.client("dynamodb", region_name=REGION)


def write_session_running():
    """Mark the session as RUNNING in DynamoDB (called at the very start)."""
    if not DYNAMO_TABLE:
        return
    try:
        client = _dynamo_client()
        now = now_iso()
        client.update_item(
            TableName=DYNAMO_TABLE,
            Key={"session_id": {"S": f"SESSION#{SESSION_ID}"}},
            UpdateExpression=(
                "SET #s = :s, target_url = :url, updated_at = :u"
                " , max_depth = :md, max_links = :ml"
            ),
            ExpressionAttributeNames={"#s": "status"},
            ExpressionAttributeValues={
                ":s":   {"S": "RUNNING"},
                ":url": {"S": BASE_URL},
                ":u":   {"S": now},
                ":md":  {"N": str(MAX_DEPTH)},
                ":ml":  {"N": str(MAX_LINKS)},
            },
        )
        print(f"DynamoDB: status=RUNNING  ({SESSION_ID})", flush=True)
    except Exception as e:
        # Non-fatal: log and continue. S3 artifacts are the source of truth.
        print(f"DynamoDB WARN (running): {e}", flush=True)


def write_session_completed(summary_stats, artifact_manifest):
    """Mark the session as COMPLETED and write summary metrics to DynamoDB."""
    if not DYNAMO_TABLE:
        return
    try:
        import json as _json
        client = _dynamo_client()
        now = now_iso()

        # Serialise summary_stats as a DynamoDB Map
        def to_dynamo_map(d):
            result = {}
            for k, v in d.items():
                if isinstance(v, int):
                    result[k] = {"N": str(v)}
                elif isinstance(v, float):
                    result[k] = {"N": str(v)}
                elif isinstance(v, str):
                    result[k] = {"S": v}
                elif v is None:
                    result[k] = {"NULL": True}
            return {"M": result}

        # artifact_manifest: {state_id: {url, timestamp}} → DynamoDB Map of Maps
        manifest_dynamo = {
            "M": {
                sid: {
                    "M": {
                        "url":       {"S": meta.get("url", "")},
                        "timestamp": {"S": meta.get("timestamp", "")},
                    }
                }
                for sid, meta in artifact_manifest.items()
            }
        }

        client.update_item(
            TableName=DYNAMO_TABLE,
            Key={"session_id": {"S": f"SESSION#{SESSION_ID}"}},
            UpdateExpression=(
                "SET #s = :s, updated_at = :u"
                ", summary_stats = :ss"
                ", artifact_manifest = :am"
            ),
            ExpressionAttributeNames={"#s": "status"},
            ExpressionAttributeValues={
                ":s":  {"S": "COMPLETED"},
                ":u":  {"S": now},
                ":ss": to_dynamo_map(summary_stats),
                ":am": manifest_dynamo,
            },
        )
        print(f"DynamoDB: status=COMPLETED ({SESSION_ID})", flush=True)
    except Exception as e:
        print(f"DynamoDB WARN (completed): {e}", flush=True)


# ── Utilities ─────────────────────────────────────────────────────────────────

def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def slug(url: str) -> str:
    p = urlparse(url)
    path = p.path.strip("/").replace("/", "_") or "home"
    return re.sub(r"[^a-z0-9_-]", "", path.lower())[:40] or "home"


def safe_label(text: str) -> str:
    t = text.encode("ascii", "ignore").decode()
    t = re.sub(r"[^a-z0-9 _-]", "", t.lower())
    t = re.sub(r"\s+", "-", t.strip())
    return t[:25] or "click"


def internal(url: str) -> bool:
    p = urlparse(url)
    if p.scheme not in ("http", "https"):
        return False
    return p.netloc == urlparse(BASE_URL).netloc


# ── Page interactions ─────────────────────────────────────────────────────────

async def scroll_page(page) -> None:
    total = await page.evaluate("document.body.scrollHeight")
    vh    = await page.evaluate("window.innerHeight")
    step  = max(vh // 3, 200)
    pos   = 0
    while pos < total:
        await page.evaluate(f"window.scrollTo({{top:{pos},behavior:'smooth'}})")
        await asyncio.sleep(0.15)
        pos += step
    await page.evaluate("window.scrollTo({top:0,behavior:'smooth'})")
    await asyncio.sleep(0.3)


async def wait_for_idle(page, timeout: int = 5000) -> None:
    try:
        await page.wait_for_load_state("networkidle", timeout=timeout)
    except Exception as e:
        print(f"WARN wait_for_idle fallback after timeout/error: {e}", flush=True)
        await asyncio.sleep(1.5)


# ── State capture ─────────────────────────────────────────────────────────────

async def capture_state(page, trigger_action: str = None, trigger_label: str = None) -> dict:
    """
    Record one visual state: screenshot + DOM metadata + transition edge.
    This is the core data unit consumed by visual QA agents.
    """
    state_ctr[0] += 1
    state_id  = f"state_{state_ctr[0]:04d}"
    ts        = now_iso()
    shot_path = f"{SCREENS_DIR}/{state_id}.png"

    await page.screenshot(path=shot_path, full_page=True)

    title = await page.title()
    url   = page.url

    try:
        scroll_y = await page.evaluate("window.scrollY")
        doc_h    = await page.evaluate("document.documentElement.scrollHeight")

        headings = await page.eval_on_selector_all(
            "h1,h2,h3",
            "els => els.slice(0,10).map(e => ({"
            "  tag: e.tagName.toLowerCase(),"
            "  text: e.innerText.trim().slice(0,120)"
            "}))"
        )
        links = await page.eval_on_selector_all(
            "a[href]",
            "els => [...new Set(els.map(e => e.href))].slice(0,25)"
        )
        preview = await page.evaluate(
            "document.body ? document.body.innerText.slice(0,600) : ''"
        )
        interactive = await page.eval_on_selector_all(
            "[role=button],[role=tab],button,summary",
            "els => els.filter(e => e.offsetParent !== null)"
            "       .slice(0,20)"
            "       .map(e => e.innerText.trim().slice(0,60))"
            "       .filter(t => t.length > 0)"
        )
    except Exception as e:
        print(f"WARN metadata capture failed for {page.url}: {e}", flush=True)
        scroll_y, doc_h, headings, links, preview, interactive = 0, 0, [], [], "", []

    state = {
        "state_id":              state_id,
        "url":                   url,
        "title":                 title,
        "timestamp":             ts,
        "screenshot":            f"screenshots/{state_id}.png",
        "scroll_y":              scroll_y,
        "document_height":       doc_h,
        "trigger_action":        trigger_action,
        "trigger_label":         trigger_label,
        "headings":              headings,
        "links_found":           links,
        "interactive_elements":  interactive,
        "visible_text_preview":  preview.strip(),
    }
    states.append(state)
    print(f"STATE {state_id} | {trigger_action} | {url} | {title!r}", flush=True)

    # Directed transition edge
    if prev_state[0] is not None:
        transitions.append({
            "from_state_id": prev_state[0]["state_id"],
            "to_state_id":   state_id,
            "action":        trigger_action or "navigation",
            "trigger_label": trigger_label or "",
            "from_url":      prev_state[0]["url"],
            "to_url":        url,
            "timestamp":     ts,
        })

    prev_state[0] = state
    return state


# ── Interactive element clicking ───────────────────────────────────────────────

async def click_interactive(page) -> None:
    selectors = [
        "[role=tab]",
        "[role=button]:not([disabled])",
        "button:not([disabled]):not([type=submit])",
        "[data-tab],[data-toggle],[data-target]",
        "details > summary",
        "[aria-selected=false]",
        "[aria-expanded=false]",
        ".accordion-header,.accordion-toggle",
    ]
    clicked_labels = set()
    click_count    = 0

    for sel in selectors:
        try:
            elements = await page.query_selector_all(sel)
            for el in elements[:8]:
                try:
                    if not await el.is_visible():
                        continue
                    if not await el.bounding_box():
                        continue
                    raw_text = (await el.inner_text()).strip()
                    label    = safe_label(raw_text)
                    if not label or label in clicked_labels:
                        continue
                    href = await el.get_attribute("href") or ""
                    if href and not href.startswith("#") and not href.startswith("javascript"):
                        target = href if href.startswith("http") else BASE_URL.rstrip("/") + "/" + href.lstrip("/")
                        if urlparse(target).netloc != urlparse(BASE_URL).netloc:
                            continue
                        if urlparse(target).path != urlparse(page.url).path:
                            continue
                    clicked_labels.add(label)
                    print(f"  CLICK [{sel}] -> {label!r}", flush=True)
                    await el.scroll_into_view_if_needed()
                    await asyncio.sleep(0.2)
                    await el.click(timeout=3000)
                    await wait_for_idle(page, timeout=6000)
                    await asyncio.sleep(0.5)
                    await capture_state(page, trigger_action="click", trigger_label=label)
                    click_count += 1
                except Exception as e:
                    print(f"  CLICK ERR: {e}", flush=True)
        except Exception as e:
            print(f"WARN selector query failed [{sel}] on {page.url}: {e}", flush=True)

    if click_count:
        print(f"  Captured {click_count} click states on {page.url}", flush=True)


# ── Page crawl ────────────────────────────────────────────────────────────────

async def crawl(page, url: str, depth: int) -> None:
    if url in seen or depth > MAX_DEPTH:
        return
    seen.add(url)
    if urlparse(url).netloc != urlparse(BASE_URL).netloc:
        print(f"SKIP external {url}")
        return
    print(f"\nPAGE [{depth}] {url}", flush=True)
    try:
        await page.goto(url, wait_until="networkidle", timeout=25000)
        if urlparse(page.url).netloc != urlparse(BASE_URL).netloc:
            print(f"SKIP redirect {page.url}")
            return
    except Exception as e:
        print(f"ERR navigating to {url}: {e}")
        return

    await asyncio.sleep(1)
    await capture_state(page, trigger_action="navigation", trigger_label=url)
    await scroll_page(page)
    await capture_state(page, trigger_action="scroll", trigger_label="scroll_to_bottom")
    await click_interactive(page)

    if depth < MAX_DEPTH:
        hrefs = await page.eval_on_selector_all("a[href]", "els => els.map(e => e.href)")
        kids  = list(
            dict.fromkeys([h for h in hrefs if internal(h) and h not in seen])
        )[:MAX_LINKS]
        for child_url in kids:
            await crawl(page, child_url, depth + 1)


# ── Title/outro cards ─────────────────────────────────────────────────────────

def card(path: str, l1: str, l2: str, l3: str = "") -> None:
    result = subprocess.run([
        "convert", "-size", "1280x800", "xc:#0d1117",
        "-fill", "#e6edf3", "-font", "DejaVu-Sans-Bold", "-pointsize", "56",
        "-gravity", "Center", "-annotate", "+0-80", l1,
        "-fill", "#58a6ff", "-font", "DejaVu-Sans",  "-pointsize", "32",
        "-gravity", "Center", "-annotate", "+0+20",  l2,
        "-fill", "#8b949e", "-pointsize", "22",
        "-gravity", "Center", "-annotate", "+0+100", l3,
        path,
    ], capture_output=True)
    if result.returncode != 0:
        stderr = result.stderr.decode("utf-8", errors="replace").strip()
        print(f"WARN failed to generate card {path}: {stderr}", flush=True)


# ── Entry point ───────────────────────────────────────────────────────────────

async def main() -> None:
    crawl_start = datetime.now(timezone.utc)

    print(f"SESSION_ID : {SESSION_ID}", flush=True)
    print(f"BASE_URL   : {BASE_URL}",   flush=True)
    print(f"MAX_DEPTH  : {MAX_DEPTH}",  flush=True)
    print(f"MAX_LINKS  : {MAX_LINKS}",  flush=True)

    # Persist session ID for the calling bash script
    with open(f"{OUT_DIR}/.session_id", "w") as fh:
        fh.write(SESSION_ID)

    # ── Signal RUNNING to DynamoDB ────────────────────────────────────────────
    write_session_running()

    card(
        f"{OUT_DIR}/0000_title.png",
        "ScreenWeave",
        urlparse(BASE_URL).netloc,
        "Visual QA Crawl",
    )

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(headless=True)
        ctx = await browser.new_context(
            viewport={"width": 1280, "height": 800},
            user_agent="Mozilla/5.0 Chrome/122",
        )
        await ctx.tracing.start(screenshots=True, snapshots=True, sources=False)
        page = await ctx.new_page()
        await crawl(page, BASE_URL, 0)
        await ctx.tracing.stop(path=TRACE_PATH)
        await browser.close()

    card(
        f"{OUT_DIR}/9999_outro.png",
        urlparse(BASE_URL).netloc,
        "ScreenWeave Visual QA",
        f"{len(states)} states captured",
    )

    # ── Write states manifest ─────────────────────────────────────────────────
    with open(f"{OUT_DIR}/states.json", "w") as fh:
        json.dump(
            {
                "session_id":   SESSION_ID,
                "base_url":     BASE_URL,
                "total_states": len(states),
                "captured_at":  now_iso(),
                "states":       states,
            },
            fh,
            indent=2,
        )

    # ── Write transitions manifest ────────────────────────────────────────────
    with open(f"{OUT_DIR}/transitions.json", "w") as fh:
        json.dump(
            {
                "session_id":        SESSION_ID,
                "total_transitions": len(transitions),
                "transitions":       transitions,
            },
            fh,
            indent=2,
        )

    crawl_end = datetime.now(timezone.utc)
    duration_sec = int((crawl_end - crawl_start).total_seconds())

    print(f"\nDONE | {len(states)} states | {len(transitions)} transitions | {duration_sec}s", flush=True)

    # ── Build artifact_manifest for DynamoDB (state_id → {url, timestamp}) ───
    artifact_manifest = {
        s["state_id"]: {
            "url":       s["url"],
            "timestamp": s["timestamp"],
        }
        for s in states
    }

    summary_stats = {
        "total_states":       len(states),
        "total_transitions":  len(transitions),
        "total_screenshots":  len(states),
        "duration_seconds":   duration_sec,
        "unique_pages":       len({s["url"] for s in states}),
    }

    # ── Signal COMPLETED to DynamoDB ─────────────────────────────────────────
    write_session_completed(summary_stats, artifact_manifest)

    print(f"SESSION_ID: {SESSION_ID}", flush=True)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except Exception as e:
        print(f"FATAL crawler failed: {e}", flush=True)
        raise
